### ISSUE TITLE
let's publish readme onto npm

### ISSUE THREAD

**Issue by revelt** [domenic/sorted-object#4]
hi all!

Currently, [page](https://www.npmjs.com/package/sorted-object) on npm doesn't display the readme:

![no readme on npm](https://user-images.githubusercontent.com/8344688/39313451-f4b08ce0-4969-11e8-96d3-3039b23fb0f0.png)

---

let's get it published on npm too!

**Comment by domenic** [comment]
Sounds like a bug with the npm website, not this package. As you can see, the README is present here.

**Comment by revelt** [comment]
we have the package.json

```
"files": [
    "lib/"
  ],
```

which publishes only contents of `lib/`, I'm wondering can it be the reason??? It shouldn't be, but..

**Comment by domenic** [comment]
No, npm always includes the README when publishing. See https://docs.npmjs.com/files/package.json#files

**Comment by revelt** [comment]
I know.. Maybe it's their new website misbehaving..
